using SAPAPP.Configs;
using System.IO;
using System.Windows;

namespace SAPAPP.AutoScripts
{
    internal class FuelGaugeScript : Script
    {

        private const int WRITE_MAX = 30;

        #region Constructors

        public FuelGaugeScript() : base()
        {
            CompatibleArchitecture = Architecture.FUELGAUGE;
            CapableAutomatic = false;
        }

        public FuelGaugeScript(Logger logger) : base(logger)
        {
            CompatibleArchitecture = Architecture.FUELGAUGE;
            CapableAutomatic = false;
        }

        public FuelGaugeScript(Logger logger, Action<string> updateFeedbackAction, Action<int> updateProgBarAction) : base(logger, updateFeedbackAction, updateProgBarAction)
        {
            CompatibleArchitecture = Architecture.FUELGAUGE;
            CapableAutomatic = false;
        }

        #endregion

        #region Search and Download algorithms

        public override bool Detect()
        {
            return false;
        }

        public override void Download(Part currentDownload)
        {
            // Open the file for reading.
            //string textFileName = Path.GetFullPath(currentDownload.FullFirmwarePath());
            string textFileName = "C:\\Users\\nbealsla\\Downloads\\pythonProgrammer\\G3_Battery_Fuel_Gauge_v1.0.df.fs";

            MessageBox.Show(textFileName);

            StreamReader textFile = new(textFileName);
            ProcessOutputData($"Opened the firmware file:      {textFileName}");

            // Create the new output file; erase a preexisting output file.
            string hFileName = Path.Combine("C:\\Users\\nbealsla\\Downloads\\pythonProgrammer\\", "data.h");

            StreamWriter hFile = new(hFileName, append:false);
            ProcessOutputData($"Created/overwrote output file: {hFileName}");

            // Add stuff to the beginning of the h file.
            string lines =  "\n/* Autogenerated by FuelGaugeProgrammer.py */\n\n" +
                            "#ifndef DATA_H\n" +
                            "#define DATA_H\n\n" +
                            "// This is data to be written to the device.\n" +
                            "#ifndef DATA_ARRAY\n" +
                            "#define DATA_ARRAY\n" +
                            "const uint8_t data[] =\n" +
                            "{//          cmd  addr  len   data\n";
            hFile.Write(lines);

            ProcessOutputData($"Encoding the following data:");

            // Step through each Line in the file.
            foreach (string fullLine in textFile.ReadToEnd().Split("\n"))
            {
                if (fullLine.Length > 0)
                {

                    // Ignore lines which start with ';'.
                    if (fullLine[0] == ';')
                    {
                        continue;
                    }

                    // For all other lines...
                    else
                    {
                        // Remove the newline character.
                        string line = fullLine.Trim();

                        // Split the string into a list of data.
                        string[] lineItems = line.Split(' ');

                        // Find the command substring (should be either 'W:', 'C:', 'X:'). 
                        string command = lineItems[0];

                        // Process the delay command "X".
                        if (command == "X:")
                        {
                            // Print the command.
                            hFile.Write($"\t(uint8_t)\'X\',");
                            ProcessOutputData($"X:");

                            // Find the number of milliseconds to delay.
                            var delay = lineItems[1];
                            var by = short.Parse(delay);

                            // Split the delay into two bytes
                            var highByte = (byte)((by >> 8) & 0xFF);    //highByte = (int(delay) >> 8) & 0xFF;
                            var lowByte = (byte)(by & 0xFF);            //lowByte = int(delay) & 0xFF

                            // Print both bytes as hexadecimal numbers.
                            hFile.Write($" 0x{highByte:X2}, 0x{lowByte:X2},");
                            hFile.Write($"\t// {delay:s} ms delay\n");
                            ProcessOutputData($"0x{highByte:X2}, 0x{lowByte},");
                            ProcessOutputData($"({delay} ms)");

                        }

                        // Process the compare command "C".
                        else if (command == "C:")
                        {
                            // Print the command.
                            hFile.Write($"\t(uint8_t)\'C\',");
                            ProcessOutputData("C:");

                            // Find the address.
                            string address = lineItems[1];

                            // Print the address.
                            hFile.Write($" 0x{address},");
                            ProcessOutputData($"0x{address},");

                            // Form list of the remaining items.
                            string[] dataItems = [.. lineItems.Skip(2)];

                            // Print the number of data items as a hexadecimal number.
                            hFile.Write($"0x{dataItems.Length:X2},");
                            ProcessOutputData($"%3d, {dataItems.Length}");

                            // Print the data items.
                            foreach (string eachItem in dataItems)
                            {
                                hFile.Write($" 0x{eachItem},");
                                ProcessOutputData($"0x{eachItem},");
                            }

                            // Print a newline.
                            hFile.WriteLine();
                        }

                        // Process the write command "W".
                        else if (command == "W:")
                        {
                            // Find the address.
                            string address = lineItems[1];

                            // Form list of the remaining items.
                            string[] dataItems = [.. lineItems.Skip(2)];

                            // Find the number of ata items.
                            int length = dataItems.Length;

                            // Remember out current position in the dataItems list.
                            int index = 0;

                            // Process all data items.
                            while (length > 0)
                            {
                                // Print the command.
                                hFile.Write($"\t(uint8_t)\'W\',");
                                ProcessOutputData($"W:");

                                // Print the address.
                                hFile.Write($" 0x{address},");
                                ProcessOutputData($"0x{address},");

                                // Split into commands of no more than 30 bytes
                                if (length > WRITE_MAX)
                                {
                                    // Print 30 (the number of data items = WRITE_MAX).
                                    hFile.Write($"0x{WRITE_MAX:X2},");
                                    ProcessOutputData($"%3d, {WRITE_MAX}");

                                    // Print the index, but not for the first packet,
                                    // because it's already there (see note at top of file).
                                    // If we aren't on the first chunk of 30...
                                    if (index == 0)
                                    {
                                        // Print the flash index, which is the first data item.
                                        hFile.Write($" 0x{dataItems[0]},");
                                        ProcessOutputData($" 0x{dataItems[0]},");

                                        // Delete the flash index from the dataItems list.
                                        dataItems = [.. dataItems.Skip(1)];
                                    }
                                    else
                                    {
                                        // Print the flash index, which we calculated
                                        hFile.Write($" 0x{index:X2},");
                                        ProcessOutputData($" 0x{index:X2},");
                                    }

                                    // Print 29 data items (29 = WRITE_MAX - 1).
                                    foreach (string eachItem in dataItems.Skip(index).Take(WRITE_MAX - 1))
                                    {
                                        hFile.Write($" 0x{eachItem},");
                                        ProcessOutputData($" 0x{eachItem},");
                                    }

                                    //subtract 29 from length (29 = WRITE_MAX - 1).
                                    length -= WRITE_MAX - 1;

                                    // Add 29 to index (29 = WRITE_MAX).
                                    index += WRITE_MAX - 1;
                                }

                                else
                                {
                                    //Print the number of data items as a hexadecimal number.
                                    hFile.Write($" 0x{length:X2},");


                                    // Print the flash index, but not for the first packet,
                                    // because it's already there (see note at top of file).
                                    // If we aren't on the first chunk of 30...
                                    if (index != 0)
                                    {
                                        // Print the flash index.
                                        hFile.Write($" 0x{index:X2},");
                                        ProcessOutputData($" 0x{index:X2},");
                                    }

                                    //Print the data items
                                    foreach (string eachItem in dataItems.Skip(index))
                                    {
                                        hFile.Write($" 0x{eachItem},");
                                        ProcessOutputData($"0x{eachItem},");
                                    }

                                    // Update length.
                                    length = 0;
                                }

                                //Print a newline.
                                hFile.WriteLine();
                            }
                        }
                        else
                        {
                            HandleError($"ERROR:  Unexpected command:  {command}");
                        }
                    }
                }
            }

            // Add stuff to the end of the h file.
            lines = "};\n" +
                    "#else\n" +
                    "extern uint8_t data[];\n" +
                    "#endif\t// DATA_ARRAY\n\n" +
                    "#endif\t// DATA_H";
            hFile.Write(lines);


            // close the input file
            textFile.Close();
            ProcessOutputData($"Closed firmware file:          {textFileName}");

            // Close the output file
            hFile.Close();
            ProcessOutputData($"Closed output file:            {hFileName}");

            ProcessOutputData($"Done!");
        }

        #endregion

        #region Feedback Filtering
        protected override void HandleError(string line)
        {
            throw new NotImplementedException();
        }

        protected override void ProcessOutputData(string data)
        {
            logger.Log(data, Logger.LogType.Info);
            UpdateMessageFeedback(data);
        }

        #endregion
    }
}
