<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Navigation.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="DropDown.xaml" />
    <Page Remove="Navigation.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="firmware\STMPrograms\" />
    <Folder Include="resources\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\PublishProfiles\ClickOnceProfile.pubxml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\SENSIT-LOGO-Options_WhiteYellow-Logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
