<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<ApplicationIcon>resources\icon.ico</ApplicationIcon>
	<LangVersion>preview</LangVersion>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\PublishProfiles\ClickOnceProfile.pubxml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
